--------------------------------------------------------
--  Constraints for Table R_FLEX_ATTRIBUTE_MGMT
--------------------------------------------------------

  ALTER TABLE "VF_SPMC_REF"."R_FLEX_ATTRIBUTE_MGMT" MODIFY ("FLEX_ATTR_DISPLAY_NAME" NOT NULL ENABLE);
  ALTER TABLE "VF_SPMC_REF"."R_FLEX_ATTRIBUTE_MGMT" MODIFY ("FLEX_ATTR_NAME" NOT NULL ENABLE);
  ALTER TABLE "VF_SPMC_REF"."R_FLEX_ATTRIBUTE_MGMT" MODIFY ("FLEX_ATTR_TYPE" NOT NULL ENABLE);
  ALTER TABLE "VF_SPMC_REF"."R_FLEX_ATTRIBUTE_MGMT" MODIFY ("FLEX_ATTR_ID" NOT NULL ENABLE);
