--------------------------------------------------------
--  Constraints for Table D_ACCOUNT_MANAGER
--------------------------------------------------------

  ALTER TABLE "D_ACCOUNT_MANAGER" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "D_ACCOUNT_MANAGER" MODIFY ("LOCAL_MARKET_CD" NOT NULL ENABLE);
  ALTER TABLE "D_ACCOUNT_MANAGER" ADD CONSTRAINT "D_ACCOUNT_MANAGER_PK" PRIMARY KEY ("ACCOUNT_MANAGER_ID") ENABLE;
  ALTER TABLE "D_ACCOUNT_MANAGER" MODIFY ("VALID_FROM_DT" NOT NULL ENABLE);
  ALTER TABLE "D_ACCOUNT_MANAGER" MODIFY ("CURRENT_FLAG" NOT NULL DISABLE);
  ALTER TABLE "D_ACCOUNT_MANAGER" MODIFY ("ACCOUNT_MANAGER_ID" NOT NULL ENABLE);
/
