--------------------------------------------------------
--  Constraints for Table D_CALENDAR_MONTH
--------------------------------------------------------

  ALTER TABLE "D_CALENDAR_MONTH" ADD CONSTRAINT "PK_MONTH_SK_ID" PRIMARY KEY ("CALENDAR_MONTH_CD") ENABLE;
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_YEAR_LONG_NAME" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_YEAR_NAME" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_YEAR_SORT" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_YEAR" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_QTR_LONG_NAME" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_QTR_NAME" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_QTR_LONG_DESC" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_QTR_DESC" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_QTR_SORT" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_QTR_CD" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_MONTH_LONG_NAME" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_MONTH_NAME" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_MONTH_LONG_DESC" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_MONTH_DESC" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_MONTH_SORT" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("FISCAL_MONTH_CD" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_YEAR" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_QTR_LONG_NAME" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_QTR_NAME" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_QTR_LONG_DESC" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_QTR_DESC" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_QTR_SORT" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_QTR_CD" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_MONTH_LONG_NAME" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_MONTH_NAME" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_MONTH_LONG_DESC" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_MONTH_DESC" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_MONTH_SORT" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_QTR_NUM" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_MONTH_NUM" NOT NULL ENABLE);
  ALTER TABLE "D_CALENDAR_MONTH" MODIFY ("CALENDAR_MONTH_CD" NOT NULL ENABLE);
/
