--------------------------------------------------------
--  Constraints for Table D_LANDSCAPE_DETAIL
--------------------------------------------------------

  ALTER TABLE "VF_SPMC_PERF"."D_LANDSCAPE_DETAIL" MODIFY ("INGEST_MONTH" NOT NULL ENABLE);
  ALTER TABLE "VF_SPMC_PERF"."D_LANDSCAPE_DETAIL" MODIFY ("LOCAL_MARKET_CD" NOT NULL ENABLE);
  ALTER TABLE "VF_SPMC_PERF"."D_LANDSCAPE_DETAIL" MODIFY ("VALID_FROM_DT" NOT NULL ENABLE);
  ALTER TABLE "VF_SPMC_PERF"."D_LANDSCAPE_DETAIL" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "VF_SPMC_PERF"."D_LANDSCAPE_DETAIL" MODIFY ("LANDSCAPE_DETAIL_ID" NOT NULL ENABLE);

