--------------------------------------------------------
--  Constraints for Table D_LOCAL_MARKET
--------------------------------------------------------

  ALTER TABLE "D_LOCAL_MARKET" ADD CONSTRAINT "D_LOCAL_MARKET_PK" PRIMARY KEY ("LOCAL_MARKET_ID") ENABLE;
  ALTER TABLE "D_LOCAL_MARKET" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "D_LOCAL_MARKET" MODIFY ("VALID_FROM_DT" NOT NULL ENABLE);
  ALTER TABLE "D_LOCAL_MARKET" MODIFY ("LOCAL_MARKET_ID" NOT NULL ENABLE);
  ALTER TABLE "D_LOCAL_MARKET" MODIFY ("CURRENT_FLAG" NOT NULL ENABLE);
/
