--------------------------------------------------------
--  Constraints for Table F_KPI_PERFORMANCE_M
--------------------------------------------------------

  ALTER TABLE "VF_SPMC_PERF"."F_KPI_PERFORMANCE_M" MODIFY ("LOCAL_MARKET_ID" NOT NULL ENABLE);
  ALTER TABLE "VF_SPMC_PERF"."F_KPI_PERFORMANCE_M" MODIFY ("ACCOUNT_MANAGER_ID" NOT NULL ENABLE);
  ALTER TABLE "VF_SPMC_PERF"."F_KPI_PERFORMANCE_M" MODIFY ("CALENDAR_MONTH_CD" NOT NULL ENABLE);

