--------------------------------------------------------
--  Constraints for Table F_LANDSCAPE_M
--------------------------------------------------------

  ALTER TABLE "F_LANDSCAPE_M" MODIFY ("LOCAL_MARKET_CD" NOT NULL ENABLE);
  ALTER TABLE "F_LANDSCAPE_M" MODIFY ("INGEST_MONTH" NOT NULL ENABLE);
  ALTER TABLE "F_LANDSCAPE_M" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "F_LANDSCAPE_M" MODIFY ("LANDSCAPE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "F_LANDSCAPE_M" MODIFY ("LOCAL_MARKET_ID" NOT NULL ENABLE);
  ALTER TABLE "F_LANDSCAPE_M" MODIFY ("ACCOUNT_MANAGER_ID" NOT NULL ENABLE);
  ALTER TABLE "F_LANDSCAPE_M" MODIFY ("CALENDAR_MONTH_CD" NOT NULL ENABLE);
/
