--------------------------------------------------------
--  DDL for Table D_ACCOUNT_MANAGER
--------------------------------------------------------

  CREATE TABLE "VF_SPMC_PERF"."D_ACCOUNT_MANAGER" 
   (	"ACCOUNT_MANAGER_ID" NUMBER, 
	"EMAIL" VARCHAR2(200), 
	"NAME" VARCHAR2(256), 
	"GRADE" VARCHAR2(50), 
	"ROLE_DESC" VARCHAR2(20), 
	"REGION_CD" VARCHAR2(10), 
	"REGION_DESC" VARCHAR2(50), 
	"HIERARCHY_LVL_1" VARCHAR2(256), 
	"HIERARCHY_LVL_2" VARCHAR2(256), 
	"HIERARCHY_LVL_3" VARCHAR2(256), 
	"HIERARCHY_LVL_4" VARCHAR2(256), 
	"HIERARCHY_LVL_5" VARCHAR2(256), 
	"CURRENT_FLAG" CHAR(1), 
	"VALID_FROM_DT" DATE, 
	"VALID_UNTIL_DT" DATE, 
	"CREATED_DT" DATE, 
	"ROLE_CD" VARCHAR2(3), 
	"INGEST_MONTH" VARCHAR2(6), 
	"LOCAL_MARKET_CD" VARCHAR2(3)
   ) ;
