--------------------------------------------------------
--  DDL for Table D_CALENDAR_MONTH
--------------------------------------------------------

  CREATE TABLE "VF_SPMC_PERF"."D_CALENDAR_MONTH" 
   (	"CALENDAR_MONTH_CD" VARCHAR2(6), 
	"CALENDAR_MONTH_NUM" NUMBER(2,0), 
	"CALENDAR_QTR_NUM" NUMBER(1,0), 
	"CALENDAR_MONTH_SORT" NUMBER(6,0), 
	"CALENDAR_MONTH_DESC" VARCHAR2(8), 
	"CALENDAR_MONTH_LONG_DESC" VARCHAR2(14), 
	"CALENDAR_MONTH_NAME" VARCHAR2(3), 
	"CALENDAR_MONTH_LONG_NAME" VARCHAR2(9), 
	"CALENDAR_QTR_CD" VARCHAR2(6), 
	"CALENDAR_QTR_SORT" NUMBER(5,0), 
	"CALENDAR_QTR_DESC" VARCHAR2(7), 
	"CALENDAR_QTR_LONG_DESC" VARCHAR2(14), 
	"CALENDAR_QTR_NAME" VARCHAR2(2), 
	"CALENDAR_QTR_LONG_NAME" VARCHAR2(9), 
	"CALENDAR_YEAR" NUMBER(4,0), 
	"FISCAL_MONTH_CD" VARCHAR2(8), 
	"FISCAL_MONTH_SORT" NUMBER(6,0), 
	"FISCAL_MONTH_DESC" VARCHAR2(9), 
	"FISCAL_MONTH_LONG_DESC" VARCHAR2(19), 
	"FISCAL_MONTH_NAME" VARCHAR2(6), 
	"FISCAL_MONTH_LONG_NAME" VARCHAR2(12), 
	"FISCAL_QTR_CD" VARCHAR2(7), 
	"FISCAL_QTR_SORT" NUMBER(5,0), 
	"FISCAL_QTR_DESC" VARCHAR2(9), 
	"FISCAL_QTR_LONG_DESC" VARCHAR2(26), 
	"FISCAL_QTR_NAME" VARCHAR2(4), 
	"FISCAL_QTR_LONG_NAME" VARCHAR2(16), 
	"FISCAL_YEAR" VARCHAR2(6), 
	"FISCAL_YEAR_SORT" NUMBER(4,0), 
	"FISCAL_YEAR_NAME" VARCHAR2(5), 
	"FISCAL_YEAR_LONG_NAME" VARCHAR2(9)
   ) ;
