--------------------------------------------------------
--  DDL for Table D_KPI_CALCULATION
--------------------------------------------------------

  CREATE TABLE "VF_SPMC_PERF"."D_KPI_CALCULATION" 
   (	"KPI_CALCULATION_ID" NUMBER, 
	"LOCAL_MARKET_ID" NUMBER, 
	"CALCULATION_NAME" VARCHAR2(20), 
	"KPI_GUIDANCE_VALUE" NUMBER(38,0), 
	"KPI_GUIDANCE_DESCRIPTION" VARCHAR2(256), 
	"VALID_FROM_DT" DATE, 
	"VALID_UNTIL_DT" DATE, 
	"KPI_TYPE" VARCHAR2(20), 
	"CALCUALTION_LOCALE" VARCHAR2(20), 
	"KPI_DESCRIPTION" VARCHAR2(100), 
	"KPI_GUIDANCE_OPERATOR" VARCHAR2(20), 
	"CURRENT_FLAG" CHAR(1), 
	"CREATED_DT" DATE
   ) ;
