GRANT CONNECT,RESOURCE to VF_SPMC_LANDING;
GRANT CONNECT,RESOURCE to VF_SPMC_STAGING;
GRANT CONNECT,RESOURCE to VF_SPMC_PERF;
GRANT CONNECT,RESOURCE to VF_SPMC_REF;
GRANT CONNECT,RESOURCE to VF_SPMC_ETL_ERROR;