REM INSERTING into VF_SPMC_REF.R_ACCOUNT_TYPE
SET DEFINE OFF;
Insert into VF_SPMC_REF.R_ACCOUNT_TYPE (ACCOUNT_TYPE_CD,ACCOUNT_TYPE_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('CUS','Customer',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_ACCOUNT_TYPE (ACCOUNT_TYPE_CD,ACCOUNT_TYPE_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('PRO','Prospect',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
