REM INSERTING into VF_SPMC_REF.R_CURRENCY
SET DEFINE OFF;
Insert into VF_SPMC_REF.R_CURRENCY (CURRENCY_CD,CURRENCY_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('INR','Indian Rupees',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
