REM INSERTING into VF_SPMC_REF.R_FORECAST_CAT
SET DEFINE OFF;
Insert into VF_SPMC_REF.R_FORECAST_CAT (FORECAST_CAT_CD,FORECAST_CAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('CLO','closed',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_FORECAST_CAT (FORECAST_CAT_CD,FORECAST_CAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('OMI','omitted',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_FORECAST_CAT (FORECAST_CAT_CD,FORECAST_CAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('PIP','pipeline',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
