REM INSERTING into VF_SPMC_REF.R_OPP_SALES_STAGE_STATUS
SET DEFINE OFF;
Insert into VF_SPMC_REF.R_OPP_SALES_STAGE_STATUS (OPP_SALES_STAGE_STAT_CD,OPP_SALES_STAGE_STAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('LOS','Lost',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_OPP_SALES_STAGE_STATUS (OPP_SALES_STAGE_STAT_CD,OPP_SALES_STAGE_STAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('OPN','Open',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_OPP_SALES_STAGE_STATUS (OPP_SALES_STAGE_STAT_CD,OPP_SALES_STAGE_STAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('WON','Won',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
