REM INSERTING into VF_SPMC_REF.R_OPP_SALES_METHOD
SET DEFINE OFF;
Insert into VF_SPMC_REF.R_OPP_SALES_METHOD (OPP_SALES_METHOD_CD,OPP_SALES_METHOD_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('MOB','1 - Mobile',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_OPP_SALES_METHOD (OPP_SALES_METHOD_CD,OPP_SALES_METHOD_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('FIX','2 - Fixed',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_OPP_SALES_METHOD (OPP_SALES_METHOD_CD,OPP_SALES_METHOD_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('TEN','3 - Tenders',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
