REM INSERTING into VF_SPMC_REF.R_PORTFOLIO_CAT
SET DEFINE OFF;
Insert into VF_SPMC_REF.R_PORTFOLIO_CAT (PORTFOLIO_CAT_CD,PORTFOLIO_CAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('CAP','Cloud Applications',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_PORTFOLIO_CAT (PORTFOLIO_CAT_CD,PORTFOLIO_CAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('CON','Connectivity',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_PORTFOLIO_CAT (PORTFOLIO_CAT_CD,PORTFOLIO_CAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('CSA','Connectivity and Secure Access',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_PORTFOLIO_CAT (PORTFOLIO_CAT_CD,PORTFOLIO_CAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('MTM','Machine to Machine',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_PORTFOLIO_CAT (PORTFOLIO_CAT_CD,PORTFOLIO_CAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('SER','Services',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_PORTFOLIO_CAT (PORTFOLIO_CAT_CD,PORTFOLIO_CAT_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('UCI','Unified Comms and Customer Interaction',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
