REM INSERTING into VF_SPMC_REF.R_REVENUE_TYPE
SET DEFINE OFF;
Insert into VF_SPMC_REF.R_REVENUE_TYPE (REVENUE_TYPE_CD,REVENUE_TYPE_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('MOB','Mobile',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_REVENUE_TYPE (REVENUE_TYPE_CD,REVENUE_TYPE_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('FIX','Fixed',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
