REM INSERTING into VF_SPMC_REF.R_SALES_SEG
SET DEFINE OFF;
Insert into VF_SPMC_REF.R_SALES_SEG (SALES_SEG_CD,SALES_SEG_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('LCO','Local Corporate',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_SALES_SEG (SALES_SEG_CD,SALES_SEG_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('MAS','Macro Segment',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_SALES_SEG (SALES_SEG_CD,SALES_SEG_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('PUB','Public',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_SALES_SEG (SALES_SEG_CD,SALES_SEG_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('SME','SME',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_SALES_SEG (SALES_SEG_CD,SALES_SEG_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('SOH','SOHO',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_SALES_SEG (SALES_SEG_CD,SALES_SEG_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('VGE','VGE',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
