REM INSERTING into VF_SPMC_REF.R_SOURCE_FILES
SET DEFINE OFF;
Insert into VF_SPMC_REF.R_SOURCE_FILES (SOURCE_FILE_ID,SOURCE_FILE_TYPE,SOURCE_FILE_NAME) values (1,'SALES_PROFESSIONAL','ALL.SALES_PROFESSIONAL.csv');
Insert into VF_SPMC_REF.R_SOURCE_FILES (SOURCE_FILE_ID,SOURCE_FILE_TYPE,SOURCE_FILE_NAME) values (2,'REVENUE','ZA.REV.20150101.1.csv');
Insert into VF_SPMC_REF.R_SOURCE_FILES (SOURCE_FILE_ID,SOURCE_FILE_TYPE,SOURCE_FILE_NAME) values (3,'REVENUE_TARGET','ZA.REV_TARGET.20150101.1.csv');
Insert into VF_SPMC_REF.R_SOURCE_FILES (SOURCE_FILE_ID,SOURCE_FILE_TYPE,SOURCE_FILE_NAME) values (4,'OPPORTUNITIES','ZA.OPP.20150101.1.csv');
