REM INSERTING into VF_SPMC_REF.R_TABLE_CONTROL_DATES
SET DEFINE OFF;
Insert into VF_SPMC_REF.R_TABLE_CONTROL_DATES (TABLE_NAME,COLUMN_NAME,CURRENT_FLAG,VALID_FROM,VALID_UNTIL) values ('F_REVENUE_TARGET_M','CALENDAR_MONTH_CD','1',to_date('09-MAR-15','DD-MON-RR'),to_date('09-MAR-15','DD-MON-RR'));
Insert into VF_SPMC_REF.R_TABLE_CONTROL_DATES (TABLE_NAME,COLUMN_NAME,CURRENT_FLAG,VALID_FROM,VALID_UNTIL) values ('F_REVENUE_M','CALENDAR_MONTH_CD','1',to_date('09-MAR-15','DD-MON-RR'),to_date('09-MAR-15','DD-MON-RR'));
Insert into VF_SPMC_REF.R_TABLE_CONTROL_DATES (TABLE_NAME,COLUMN_NAME,CURRENT_FLAG,VALID_FROM,VALID_UNTIL) values ('F_REVENUE_FORECAST_M','CALENDAR_MONTH_CD','1',to_date('09-MAR-15','DD-MON-RR'),to_date('09-MAR-15','DD-MON-RR'));
Insert into VF_SPMC_REF.R_TABLE_CONTROL_DATES (TABLE_NAME,COLUMN_NAME,CURRENT_FLAG,VALID_FROM,VALID_UNTIL) values ('F_OPPORTUNITY_M','CALENDAR_MONTH_CD','1',to_date('09-MAR-15','DD-MON-RR'),to_date('09-MAR-15','DD-MON-RR'));
Insert into VF_SPMC_REF.R_TABLE_CONTROL_DATES (TABLE_NAME,COLUMN_NAME,CURRENT_FLAG,VALID_FROM,VALID_UNTIL) values ('F_LANDSCAPE_M','CALENDAR_MONTH_CD','1',to_date('09-MAR-15','DD-MON-RR'),to_date('09-MAR-15','DD-MON-RR'));
Insert into VF_SPMC_REF.R_TABLE_CONTROL_DATES (TABLE_NAME,COLUMN_NAME,CURRENT_FLAG,VALID_FROM,VALID_UNTIL) values ('F_KPI_PERFORMANCE_M','CALENDAR_MONTH_CD','1',to_date('09-MAR-15','DD-MON-RR'),to_date('09-MAR-15','DD-MON-RR'));
