REM INSERTING into VF_SPMC_REF.R_TARGET_TYPE
SET DEFINE OFF;
Insert into VF_SPMC_REF.R_TARGET_TYPE (TARGET_TYPE_CD,TARGET_TYPE_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('COM','Combined',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
Insert into VF_SPMC_REF.R_TARGET_TYPE (TARGET_TYPE_CD,TARGET_TYPE_DESC,CREATION_DT,CURR_FLAG_YN,VALID_FROM_DT,VALID_UNTIL_DT) values ('NEW','New',to_date('05-MAR-15','DD-MON-RR'),'Y',to_date('05-MAR-15','DD-MON-RR'),null);
