--------------------------------------------------------
--  DDL for Table STG_REVENUE_TARGET
--------------------------------------------------------

  CREATE TABLE "VF_SPMC_STAGING"."STG_REVENUE_TARGET" 
   (	"CALENDAR_MONTH_CD" VARCHAR2(6), 
	"LOCAL_MARKET_ID" NUMBER, 
	"ACCOUNT_MANAGER_ID" NUMBER, 
	"REVENUE_TARGET" NUMBER, 
	"REVENUE_TARGET_TYPE_DESC" VARCHAR2(20), 
	"REVENUE_TARGET_TYPE_CD" VARCHAR2(20), 
	"CREATED_DT" DATE, 
	"INGEST_MONTH" VARCHAR2(6), 
	"LOCAL_MARKET_CD" VARCHAR2(3)
   ) ;
