--------------------------------------------------------
--  DDL for Table STG_SALES_PROFESSIONAL
--------------------------------------------------------

  CREATE TABLE "VF_SPMC_STAGING"."STG_SALES_PROFESSIONAL" 
   (	"EMAIL" VARCHAR2(200), 
	"GRADE" VARCHAR2(50), 
	"NAME" VARCHAR2(256), 
	"ALIAS_ACC_NAME" VARCHAR2(256), 
	"ALIAS_OPP_NAME" VARCHAR2(256), 
	"ALIAS_REV_NAME" VARCHAR2(256), 
	"REGION" VARCHAR2(50), 
	"ROLE" VARCHAR2(10), 
	"HIERARCHY_LVL_5" VARCHAR2(256), 
	"HIERARCHY_LVL_4" VARCHAR2(256), 
	"HIERARCHY_LVL_3" VARCHAR2(256), 
	"HIERARCHY_LVL_2" VARCHAR2(256), 
	"HIERARCHY_LVL_1" VARCHAR2(256), 
	"LOCAL_MARKET" VARCHAR2(3)
   ) ;
