GRANT CREATE ANY TABLE TO vf_spmc_ref;
GRANT CREATE ANY TABLE TO vf_spmc_landing;
GRANT CREATE ANY TABLE TO vf_spmc_staging;
GRANT CREATE ANY TABLE TO vf_spmc_perf;
GRANT CREATE ANY TABLE TO vf_spmc_etl_error;