GRANT SELECT ANY TABLE to VF_SPMC_PERF;
GRANT INSERT ANY TABLE to VF_SPMC_PERF;
GRANT UPDATE ANY TABLE to VF_SPMC_PERF;
GRANT DELETE ANY TABLE to VF_SPMC_PERF;

GRANT SELECT ANY TABLE to VF_SPMC_REF;
GRANT INSERT ANY TABLE to VF_SPMC_REF;
GRANT UPDATE ANY TABLE to VF_SPMC_REF;
GRANT DELETE ANY TABLE to VF_SPMC_REF;

GRANT SELECT ANY TABLE to VF_SPMC_STAGING;
GRANT INSERT ANY TABLE to VF_SPMC_STAGING;
GRANT UPDATE ANY TABLE to VF_SPMC_STAGING;
GRANT DELETE ANY TABLE to VF_SPMC_STAGING;

GRANT SELECT ANY TABLE to VF_SPMC_LANDING;
GRANT INSERT ANY TABLE to VF_SPMC_LANDING;
GRANT UPDATE ANY TABLE to VF_SPMC_LANDING;
GRANT DELETE ANY TABLE to VF_SPMC_LANDING;

