
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_MAIN_SALES_CHAN to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_MICRO_SEG to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_OPP_DEAL_TYPE to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_OPP_SALES_METHOD to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_OPP_SALES_STAGE_STATUS to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_PORTFOLIO_CAT to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_PRODUCT_FAMILY to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_PRODUCT_LINE to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_REGION to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_REVENUE_TYPE to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_SALES_SEG to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_STAGE to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_STUCK_OPPORTUNITY to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_TARGET_TYPE to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_SOURCE_FILES_LOADHIST to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_GRADE to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_FORECAST_CAT to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_CURRENCY to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_ACCOUNT_TYPE to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_SOURCE_FILES to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_LOCAL_MARKET to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_KPI_CALCULATION to VF_SPMC_LANDING;
GRANT SELECT, INSERT, UPDATE, DELETE on VF_SPMC_REF.R_OPP_STATUS to VF_SPMC_LANDING;

GRANT CREATE ANY TABLE TO VF_SPMC_LANDING;